apps/api/urls.py
from django.urls import path
from . import views

app_name = "api"
urlpatterns = [
    path('user/data/', views.userData, name='userdata'),
    path('node/data/', views.nodeData, name='nodedata'),
    path('donate/data/', views.donateData, name='donatedata'),
    path('random/port/', views.change_ss_port, name='changessport'),
    path('gen/invitecode/', views.gen_invite_code, name='geninvitecode'),
    path('shop/', views.purchase, name='purchase'),
    path('pay/request/', views.pay_request, name='pay_request'),
    path('pay/query/', views.pay_query, name='pay_query'),
    path('traffic/query/', views.traffic_query, name='traffic_query'),
    path('change/theme/', views.change_theme, name='change_theme'),
    path('checkin/', views.checkin, name='checkin'),
    # 邀请码接口
    path('get/invitecode/', views.get_invitecode),
    # web api 接口
    path('nodes/<int:node_id>', views.node_api),
    path('nodes/online', views.node_online_api),
    path('users/nodes/<int:node_id>', views.user_api),
    path('traffic/upload', views.traffic_api),
    path('nodes/aliveip', views.alive_ip_api),
]

apps/sspanel/urls.py
from django.urls import path
from .import views


app_name = "sspanel"
urlpatterns = [
    # 网站用户面板
    path('index/', views.index, name='index'),
    path('sshelp/', views.sshelp, name='sshelp'),
    path('ssclient/', views.ssclient, name='ssclient'),
    path('ssinvite/', views.ssinvite, name='ssinvite'),
    path('passinvite/(<invitecode>)/',
         views.pass_invitecode, name='passinvitecode'),
    # 注册/登录
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    # 节点
    path('nodeinfo/', views.nodeinfo, name='nodeinfo'),
    path('trafficlog/', views.trafficlog, name='trafficlog'),
    # 用户信息
    path('users/userinfo/', views.userinfo, name='userinfo'),
    path('users/userinfoedit/', views.userinfo_edit, name='userinfo_edit'),
    #  二维码
    path('qrcode/ssr/<node_id>/',
         views.get_ssr_qrcode, name='ssrqrcode'),
    path('qrcode/ss/<node_id>/',
         views.get_ss_qrcode, name='ssqrcode'),
    # 捐赠/充值
    path('donate/', views.donate, name='donate'),
    path('shop/', views.shop, name='shop'),
    path('purchaselog/', views.purchaselog, name='purchaselog'),
    path('chargecenter/', views.chargecenter, name='chargecenter'),
    path('charge/', views.charge, name='charge'),
    # 公告
    path('announcement/', views.announcement, name='announcement'),
    # 工单
    path('ticket/', views.ticket, name='ticket'),
    path('ticket/create/', views.ticket_create, name='ticket_create'),
    path('ticket/edit/(<int:pk>)/',
         views.ticket_edit, name='ticket_edit'),
    path('ticket/delete/<int:pk>)/',
         views.ticket_delete, name='ticket_delete'),
    # 推广相关
    path('affiliate/', views.affiliate, name='affiliate'),
    path('rebate/record/', views.rebate_record, name='rebate'),
    # 网站后台面板
    path('backend/', views.backend_index, name='backend_index'),
    # 邀请码相关
    path('backend/invite/', views.backend_invite, name='backend_invite'),
    path('invite_gen_code/', views.gen_invite_code, name='geninvitecode'),
    # 节点相关
    path('backend/nodeinfo/', views.backend_node_info,
         name='backend_node_info'),
    path('backend/node/delete/<int:node_id>/',
         views.node_delete, name='node_delete'),
    path('backend/node/edit/<int:node_id>/',
         views.node_edit, name='node_edit'),
    path('backend/node/create/', views.node_create, name='node_create'),
    # 用户相关
    path('backend/userlist/', views.backend_userlist, name='user_list'),
    path('backend/user/delete/<int:pk>/',
         views.user_delete, name='user_delete'),
    path('backend/user/search/', views.user_search, name='user_search'),
    path('backend/user/status/', views.user_status, name='user_status'),
    # 商品充值相关
    path('backend/charge/', views.backend_charge, name='backend_charge'),
    path('backend/shop/', views.backend_shop, name='backend_shop'),
    path('backend/shop/delete/<int:pk>/',
         views.good_delete, name='good_delete'),
    path('backend/good/create/', views.good_create, name='good_create'),
    path('backend/good/edit/<int:pk>/',
         views.good_edit, name='good_edit'),
    path('backend/purchase/history/',
         views.purchase_history, name='purchase_history'),
    # 支付宝当面付相关:
    path('facepay/qrcode/', views.gen_face_pay_qrcode, name='facepay_qrcode'),
    # 公告管理相关
    path('backend/anno/', views.backend_anno, name='backend_anno'),
    path('backend/anno/delete/<int:pk>/',
         views.anno_delete, name='anno_delete'),
    path('backend/anno/create/', views.anno_create, name='anno_create'),
    path('backend/anno/edit/<int:pk>/',
         views.anno_edit, name='anno_edit'),
    # 工单相关
    path('backend/ticket/', views.backend_ticket, name='backend_ticket'),
    path('backend/ticket/edit/<int:pk>/',
         views.backend_ticketedit, name='backend_ticketedit'),
    # 在线ip
    path('backend/aliveuser/', views.backend_alive_user, name='alive_user'),

]

apps/ssserver/urls.py
# from django.conf.urls import url
from django.urls import path
from .import views


app_name = "ssserver"
urlpatterns = [
    path('changesspass/', views.ChangeSsPass, name='changesspass'),
    path('user/edit/<int:pk>/', views.User_edit, name='user_edit'),
    path('changessmethod/', views.ChangeSsMethod, name='changessmethod'),
    path('changessprotocol/', views.ChangeSsProtocol, name='changessprotocol'),
    path('changessobfs/', views.ChangeSsObfs, name='changessobfs'),
    path('subscribe/<token>/', views.subscribe, name='subscribe'),
    path('node/config/', views.node_config, name='node_config'),
]

apps/urls.py
from django.urls import path, include
from django.contrib import admin

from apps.sspanel.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('jet/', include('jet.urls', 'jet')),

    path('', include('django.contrib.auth.urls')),
    path('', index, name="index"),
    path('sspanel/', include('apps.sspanel.urls', namespace='sspanel')),
    path('server/', include('apps.ssserver.urls', namespace='ssserver')),
    path('api/', include('apps.api.urls', namespace='api')),
]

apps/sspanel/models.py
import base64
import time
import datetime

import markdown
from decimal import Decimal
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.db import transaction
from django.contrib.auth.models import AbstractUser
from django.core.validators import MaxValueValidator, MinValueValidator

from apps.payments import alipay
from apps.constants import THEME_CHOICES
from apps.utils import get_long_random_string, traffic_format


class User(AbstractUser):
    '''SS账户模型'''

    @classmethod
    def proUser(cls):
        '''付费用户数量'''
        return len(cls.objects.filter(level__gt=0))

    @classmethod
    def userNum(cls):
        '''返回用户总数'''
        return len(cls.objects.all())

    @classmethod
    def todayRegister(cls):
        '''返回今日注册的用户'''
        today = datetime.datetime.combine(datetime.date.today(),
                                          datetime.time.min)
        return cls.objects.filter(date_joined__gt=today)

    invitecode = models.CharField(verbose_name='邀请码', max_length=40)
    invited_by = models.PositiveIntegerField(verbose_name='邀请人id', default=1)
    balance = models.DecimalField(verbose_name='余额', decimal_places=2,
                                  max_digits=10, default=0, editable=True,
                                  null=True, blank=True,)
    invitecode_num = models.PositiveIntegerField(
        verbose_name='可生成的邀请码数量', default=settings.INVITE_NUM)
    level = models.PositiveIntegerField(verbose_name='用户等级', default=0,
                                        validators=[MaxValueValidator(9),
                                                    MinValueValidator(0), ])
    level_expire_time = models.DateTimeField(verbose_name='等级有效期',
                                             default=timezone.now)
    theme = models.CharField(verbose_name='主题', choices=THEME_CHOICES,
                             default=settings.DEFAULT_THEME, max_length=10)

    def __str__(self):
        return self.username

    def get_expire_time(self):
        '''返回等级到期时间'''
        return self.level_expire_time

    def get_sub_link(self):
        '''生成该用户的订阅地址'''
        token = base64.b64encode(bytes(self.username, 'utf-8')).decode('ascii')
        sub_link = settings.HOST + 'server/subscribe/' + token + '/'
        return sub_link

    class Meta(AbstractUser.Meta):
        verbose_name = '用户'


class InviteCode(models.Model):
    '''邀请码'''

    INVITE_CODE_TYPE = ((1, '公开'), (0, '不公开'))

    code_type = models.IntegerField(
        verbose_name='类型', choices=INVITE_CODE_TYPE, default=0,)
    code_id = models.PositiveIntegerField(verbose_name='邀请人ID', default=1)
    code = models.CharField(verbose_name='邀请码', primary_key=True, blank=True,
                            max_length=40, default=get_long_random_string)
    time_created = models.DateTimeField(
        verbose_name='创建时间', editable=False, auto_now_add=True)
    isused = models.BooleanField(verbose_name='是否使用', default=False,)

    def __str__(self):
        return str(self.code)

    class Meta:
        verbose_name_plural = '邀请码'
        ordering = (
            'isused',
            '-time_created',
        )


class RebateRecord(models.Model):
    '''返利记录'''

    user_id = models.PositiveIntegerField(verbose_name='返利人ID', default=1)
    rebatetime = models.DateTimeField(
        verbose_name='返利时间', editable=False, auto_now_add=True)
    money = models.DecimalField(
        verbose_name='金额', decimal_places=2, null=True, default=0, max_digits=10, blank=True)

    class Meta:
        ordering = ('-rebatetime', )


class Donate(models.Model):
    @classmethod
    def totalDonateMoney(cls):
        '''返回捐赠总金额'''
        return sum([d.money for d in cls.objects.all()])

    @classmethod
    def totalDonateNums(cls):
        '''返回捐赠总数量'''
        return len(cls.objects.all())

    @classmethod
    def richPeople(cls):
        '''返回捐赠金额最多的前10名'''
        rec = {}
        for d in cls.objects.all():
            if d.user not in rec.keys():
                rec[d.user] = d.money
            else:
                rec[d.user] += d.money
        return sorted(rec.items(), key=lambda rec: rec[1], reverse=True)[:10]

    '''捐赠记录'''
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name='捐赠人')
    time = models.DateTimeField('捐赠时间', editable=False, auto_now_add=True)
    money = models.DecimalField(
        verbose_name='捐赠金额', decimal_places=2, max_digits=10, default=0, null=True, blank=True)

    def __str__(self):
        return '{}-{}'.format(self.user, self.money)

    class Meta:
        verbose_name_plural = '捐赠记录'
        ordering = ('-time', )


class MoneyCode(models.Model):
    '''充值码'''
    user = models.CharField(
        verbose_name='用户名', max_length=128, blank=True, null=True)
    time = models.DateTimeField('捐赠时间', editable=False, auto_now_add=True)
    code = models.CharField(verbose_name='充值码', unique=True,
                            blank=True, max_length=40, default=get_long_random_string)
    number = models.DecimalField(
        verbose_name='捐赠金额', decimal_places=2, max_digits=10, default=10, null=True, blank=True)
    isused = models.BooleanField(verbose_name='是否使用', default=False)

    def clean(self):
        # 保证充值码不会重复
        code_length = len(self.code or '')
        if 0 < code_length < 12:
            self.code = '{}{}'.format(self.code, get_long_random_string())
        else:
            self.code = get_long_random_string()

    def __str__(self):
        return self.code

    class Meta:
        verbose_name_plural = '充值码'
        ordering = ('isused', )


class Goods(models.Model):
    '''商品'''

    STATUS_TYPE = (
        (1, '上架'),
        (-1, '下架'),
    )

    name = models.CharField(verbose_name='商品名字', max_length=128, default='待编辑')
    content = models.CharField(
        verbose_name='商品描述', max_length=256, default='待编辑')
    transfer = models.BigIntegerField(
        verbose_name='增加的流量', default=settings.GB)
    money = models.DecimalField(
        verbose_name='金额', decimal_places=2, max_digits=10, default=0, null=True, blank=True)
    level = models.PositiveIntegerField(verbose_name='设置等级', default=0, validators=[
                                        MaxValueValidator(9), MinValueValidator(0), ])
    days = models.PositiveIntegerField(verbose_name='设置等级时间(天)', default=1, validators=[
        MaxValueValidator(365), MinValueValidator(1)])
    status = models.SmallIntegerField('商品状态', default=1, choices=STATUS_TYPE)
    order = models.PositiveSmallIntegerField('排序', default=1)

    def __str__(self):
        return self.name

    def get_transfer(self):
        '''增加的流量'''
        return traffic_format(self.transfer)

    def get_days(self):
        '''返回增加的天数'''
        return '{}'.format(self.days)

    class Meta:
        verbose_name_plural = '商品'
        ordering = [
            'order',
        ]


class PurchaseHistory(models.Model):
    '''购买记录'''

    good = models.ForeignKey(
        Goods, on_delete=models.CASCADE, verbose_name='商品名')
    user = models.CharField(verbose_name='购买者', max_length=128)
    money = models.DecimalField(
        verbose_name='金额', decimal_places=2, max_digits=10, default=0, null=True, blank=True)
    purchtime = models.DateTimeField('购买时间', editable=False, auto_now_add=True)

    def __str__(self):
        return self.user

    class Meta:
        verbose_name_plural = '购买记录'
        ordering = ('-purchtime', )


class PayRecord(models.Model):
    '''充值流水单号记录'''

    username = models.CharField(
        verbose_name='用户名', max_length=64, blank=False, null=False)
    info_code = models.CharField(
        verbose_name='流水号', max_length=64, unique=True)
    time = models.DateTimeField(verbose_name='时间', auto_now_add=True)
    amount = models.DecimalField(
        verbose_name='金额', decimal_places=2, max_digits=10, default=0, null=True, blank=True)
    money_code = models.CharField(
        verbose_name='充值码', max_length=64, unique=True)
    charge_type = models.CharField(verbose_name='充值类型', max_length=10,
                                   default=1,
                                   help_text='1：支付宝 2：QQ钱包 3：微信支付')

    def __str__(self):
        return self.info_code

    class Meta:
        verbose_name_plural = '支付转账记录'
        ordering = ('-time', )


class PayRequest(models.Model):
    '''支付申请记录'''

    username = models.CharField(
        verbose_name='用户名', max_length=64, blank=False, null=False)
    info_code = models.CharField(
        verbose_name='流水号', max_length=64, unique=True)
    time = models.DateTimeField('时间', auto_now_add=True)
    qrcode_url = models.CharField(
        verbose_name='支付连接', max_length=64, null=True)
    amount = models.DecimalField(verbose_name='金额', decimal_places=2,
                                 max_digits=10, default=0,
                                 null=True, blank=True)
    charge_type = models.CharField(verbose_name='充值类型', max_length=10,
                                   default=1,
                                   help_text='1：支付宝 2：QQ钱包 3：微信支付')

    def __str__(self):
        return self.username

    @classmethod
    def make_pay_request(cls, user, amount):
        '''生成一个支付请求'''
        info_code = datetime.datetime.fromtimestamp(
            time.time()).strftime('%Y%m%d%H%M%S%s')
        try:
            # 生成订单
            trade = alipay.api_alipay_trade_precreate(
                subject=settings.ALIPAY_TRADE_INFO.format(amount),
                out_trade_no=info_code,
                total_amount=amount,
                timeout_express='60s',
            )
            qrcode_url = trade.get('qr_code')
            req = cls.objects.create(
                username=user.username,
                info_code=info_code,
                amount=amount,
                qrcode_url=qrcode_url,
            )
            return req
        except:
            alipay.api_alipay_trade_cancel(out_trade_no=info_code)
            return None

templates/backend/annoedit.html
 {% extends 'backendbase.html' %} {% block main %} {% load ehcofilter %}

<div class="column is-12">
    <section class="hero is-light is-smaill">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    公告编辑：
                </h1>
                <h2 class="subtitle">
                    格式采用Markdown！
                </h2>
            </div>
        </div>
    </section>
</div>
<div class="column is-12">
    <div class="box">
        <form class="form" method="post">
            {% csrf_token %}
            <div class="control is-loading">
                <textarea class="textarea" id="id-markdown-body" name="body" type="text" rows="10">{{ anno.body }}</textarea>
            </div>
            <hr/>
            <div class="is-grouped">
                <button type="submit" class="button is-danger is-outlined ">确认修改</button>
                <a class="button is-success is-outlined" href="{% url 'sspanel:backend_anno' %}">取消修改</a>
            </div>
        </form>
    </div>
</div>
<script>
    var simplemde = new SimpleMDE({ spellChecker: false,element: $("#id-markdown-body")[0] });
</script> {% endblock main %}

templates/backend/annolist.html
{% extends 'backendbase.html' %} {% block main %}


<div class="column is-12">
    <section class="hero is-light is-smaill">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    公告列表：
                </h1>
                <h2 class="subtitle">
                    领导请下放通知!
                </h2>
            </div>
        </div>
    </section>
</div>
<div class="column is-12">
    <div class="box">
        <table class="table is-fullwidth">
            <thead>
                <tr>
                    <th>操作:</th>
                    <th>ID:</th>
                    <th>日期</th>
                    <th>内容:</th>
                </tr>
            </thead>
            {% for rec in anno %}
            <tr>
                <td>
                    <p class="control">
                        <a class="button is-info" href="{% url 'sspanel:anno_edit' rec.pk %}">编辑</a>
                    </p>
                    <p class="control">
                        <a class="button is-danger modal-button" data-target="modal-{{ rec.pk }}">删除</a>
                    </p>
                </td>
                <td>#{{ rec.pk}}</td>
                <td>{{ rec.time }}</td>
                <td>{{ rec.body |safe }}</td>
            </tr>
            <div class="modal user_delete" id="modal-{{ rec.pk }}">
                <div class="modal-background"></div>
                <div class="modal-card">
                    <header class="modal-card-head">
                        <p class="modal-card-title">ID:{{ rec.pk }}</p>
                        <button class="delete"></button>
                    </header>
                    <section class="modal-card-body">
                        <p class="subtitle">确定要删除:
                            <code>{{ rec.pk }}</code>号公告么?</p>
                        <p align="center">
                            <a class="button is-danger is-outlined" href="{% url 'sspanel:anno_delete' rec.pk %}">确定删除</a>
                        </p>
                    </section>
                </div>
            </div>
            {% empty %}
            <p class="subtitle">没有公告哟</p>
            {% endfor %}
        </table>
        <p align="right">
            <a class="button is-danger is-outlined" href="{% url 'sspanel:anno_create' %}">增加公告</a>
        </p>
    </div>
</div>

{% endblock main %}

templates/backend/goodcreate.html
 {% extends 'backendbase.html' %} {% block main %} {% load ehcofilter %}

<div class="column is-12">
    <section class="hero is-light is-smaill">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    创建新的商品：
                </h1>
                <h2 class="subtitle">
                    请在下方填写符合规则的商品信息
                </h2>
            </div>
        </div>
    </section>
</div>
<div class="column is-12">
    <div class="box">
        <form class="form" method="post">
            {% csrf_token %} {{ form.non_field_errors }} {% for field in form %} {{ field.label_tag }} {{ field|add_class:"input" }}
            {{ field.errors }} {% if field.help_text %}
            <p class="help is-danger">{{ field.help_text|safe }}</p>
            {% endif %} {% endfor %}
            <hr/>
            <div class="is-grouped">
                <button type="submit" class="button is-danger is-outlined ">确认</button>
                <a class="button is-success is-outlined" href="{% url 'sspanel:backend_shop' %}">取消</a>
            </div>
        </form>
    </div>
</div>

{% endblock main %}

templates/backend/index.html
{% extends 'backendbase.html' %} {% block main %}
<div class="column is-12">
    <section class="hero is-light is-smaill">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    汇总：
                </h1>
                <h2 class="subtitle">
                    下面是系统运行状态简报：
                </h2>
            </div>
        </div>
    </section>
</div>
<div class="column is-12">
    <div class="tile is-ancestor">
        <div class="tile is-6 is-vertical is-parent">
            <div class="tile is-child box">
                <canvas id="userState" width="auto" height="300"></canvas>
            </div>
        </div>
        <div class="tile is-6 is-vertical is-parent">
            <div class="tile is-child box">
                <canvas id="nodeState"></canvas>
            </div>
            <div class="tile is-child box">
                <canvas id="donateState"></canvas>
            </div>
        </div>
    </div>
</div>
<script>
    // 获取后台首页状态
    var getSystemStatus = function () {
        $.getJSON("{% url 'api:userdata' %}", function (results) {
            genDoughnutChart('userState', '总用户:{{ userNum }} ', ['在线人数','今日注册', '今日签到', '从未签到', '从未使用'], results.data)
        })

        $.getJSON("{% url 'api:nodedata' %}", function (results) {
            genDoughnutChart('nodeState', '节点流量 单位：GB', results.nodeName, results.nodeTraffic)
        })

        $.getJSON("{% url 'api:donatedata' %}", function (results) {
            genDoughnutChart('donateState', '收入分析', ['成交数 (笔)', '成交金额 (元)'], results.data)
        })
    }
    getSystemStatus()
</script> {% endblock main %}

templates/backend/shop.html
{% extends 'backendbase.html' %} {% block main %}
<div class="column is-12">
    <section class="hero is-light is-smaill">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    商品列表：
                </h1>
                <h2 class="subtitle">
                    添加或者删除商品：
                </h2>
            </div>
        </div>
    </section>
</div>
<div class="column is-12">
    <div class="box">
        <table class="table is-fullwidth">
            <thead>
                <tr>
                    <th>操作:</th>
                    <th>ID:</th>
                    <th>商品描述:</th>
                    <th>金额:</th>
                    <th>流量:</th>
                    <th>等级:</th>
                </tr>
            </thead>
            {% for good in goods %}
            <tr>
                <td>
                    <p class="control">
                        <a class="button is-info" href="{% url 'sspanel:good_edit' good.pk  %}">编辑</a>
                    </p>
                    <p class="control">
                        <a class="button is-danger modal-button" data-target="modal-{{ good.pk }}">删除</a>
                    </p>
                </td>
                <td>#{{ good.pk }}</td>
                <td>{{ good.name }}</td>
                <td>{{ good.money }}</td>
                <td>{{ good.get_transfer }}</td>
                <td>{{ good.level }}</td>
            </tr>
            <div class="modal node_delete" id="modal-{{ good.pk }}">
                <div class="modal-background"></div>
                <div class="modal-card">
                    <header class="modal-card-head">
                        <p class="modal-card-title">商品名:{{ good.name }}</p>
                        <button class="delete"></button>
                    </header>
                    <section class="modal-card-body">
                        <p class="subtitle">确定要删除:
                            <code>{{ good.name }}</code>?</p>
                        <p align="center">
                            <a class="button is-danger is-outlined" href="{% url 'sspanel:good_delete' good.pk %}">确定删除</a>
                        </p>
                    </section>
                </div>
            </div>
            {% empty %}
            <h2 class="subtitle">
                暂时没有商品，点击下方按钮添加商品
            </h2>
            {% endfor %}
        </table>
        <p align="right">
            <a class="button is-danger is-outlined" href="{% url 'sspanel:good_create' %}">增加商品</a>
        </p>
    </div>
</div>
{% endblock main %}

templates/backend/ticket.html
{% extends 'backendbase.html' %} {% block main %}

<div class="column is-12">
    <section class="hero is-light">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    工单一览：
                </h1>
                <h2 class="subtitle">
                    是是是，来看看都发生了什么
                </h2>
            </div>
        </div>
    </section>
</div>
<div class="column is-12">
    <div class="box">
        <div class="content">
            <p class="subtitle">所有工单:</p>
            <table class="table is-striped">
                <thead>
                    <tr>
                        <th>操作:</th>
                        <th>User:</th>
                        <th>时间:</th>
                        <th>标题:</th>
                        <th>状态</th>
                    </tr>
                </thead>
                {% for record in ticket %}
                <tr>
                    <td>
                        <a class="button is-danger" href="{% url 'sspanel:backend_ticketedit' record.pk %}">处理</a>
                    </td>
                    <td>{{ record.user }}</td>
                    <td>{{ record.time }}</td>
                    <td>{{ record.title }}</td>
                    <td>{{ record.get_status_display }}</td>
                </tr>
                {% empty %}
                <h2 class="subtitle">
                    没有人提意见，真棒！
                </h2>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
{% endblock main %}

templates/backend/userlist.html
 {% extends 'backendbase.html' %} {% block main %}
<div class="column is-12">
    <section class="hero is-light is-smaill">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    用户列表：
                </h1>
                <h2 class="subtitle">
                    给衣食父母们请安了!
                </h2>
            </div>
        </div>
    </section>
</div>
<div class="column is-12">
    <form method="get" action="{% url 'sspanel:user_search' %}">
        <div class="field has-addons">
            <div class="control">
                <input name="q" class="input" type="search" placeholder="用户名/邮箱 模糊搜索" required>
            </div>
            <div class="control">
                <button type="submit" class="button is-outlined is-info">搜索</button>
            </div>
        </div>
    </form>
    <br>
    <div class="box">
        <nav class="pagination">
            {% if contacts.has_previous %}
            <a class="pagination-previous" href="?page={{ contacts.previous_page_number }}">上一页</a> {% endif %} {% if contacts.has_next%}
            <a class="pagination-next" href="?page={{ contacts.next_page_number }}">下一页</a> {% endif %} {% if page %}
            <p>页码：</p>
            <ul class="pagination-list">
                {% if first %}
                <a href="?page=1" class="pagination-link">1</a>
                {% endif %} {% if left %} {% if left_has_more %}
                <span>...</span>
                {% endif %} {% for i in left %}
                <a href="?page={{ i }}" class="pagination-link">{{ i }}</a>
                {% endfor %} {% endif %}
                <a href="?page={{ page }}" class="pagination-link is-current">{{ page }}</a>
                {% if right %} {% for i in right%}
                <a href="?page={{ i }}" class="pagination-link">{{ i }}</a>
                {% endfor %} {% if right_has_more %}
                <span>...</span>
                {% endif %} {% endif %} {% if last %}
                <a href="?page={{ total }}" class="pagination-link">{{ total }}</a>
                {% endif %}
            </ul>
            {% endif %}
        </nav>
        <br>
        <table class="table is-fullwidth">
            <thead>
                <tr>
                    <th>操作:</th>
                    <th>ID:</th>
                    <th>用户名</th>
                    <th>邮箱:</th>
                    <th>端口:</th>
                    <th>已用/总流量</th>
                </tr>
            </thead>
            {% for contact in contacts %}
            <tr>
                <td>
                    <p class="control">
                        <a class="button is-info" href="{% url 'ssserver:user_edit' contact.ss_user.pk %}">编辑</a>
                    </p>
                    <p class="control">
                        <a class="button is-danger modal-button" data-target="modal-{{ contact.pk }}">删除</a>
                    </p>
                </td>
                <td>#{{ contact.pk}}</td>
                <td>{{ contact.username }}</td>
                <td>{{ contact.email }}</td>
                <td>{{ contact.ss_user.port }}</td>
                <td>{{ contact.ss_user.get_traffic }} / {{ contact.ss_user.get_transfer }}</td>
            </tr>
            <div class="modal user_delete" id="modal-{{ contact.pk }}">
                <div class="modal-background"></div>
                <div class="modal-card">
                    <header class="modal-card-head">
                        <p class="modal-card-title">用户名:{{ contact.username }}</p>
                        <button class="delete"></button>
                    </header>
                    <section class="modal-card-body">
                        <p class="subtitle">确定要删除:
                            <code>{{ contact.username }}</code>?</p>
                        <p align="center">
                            <a class="button is-danger is-outlined" href="{% url 'sspanel:user_delete' contact.pk %}">确定删除</a>
                        </p>
                    </section>
                </div>
            </div>
            {% empty %}
            <p class="subtitle">没有用户哟</p>
            {% endfor %}
        </table>
    </div>
</div>
{% endblock main %}